### ISSUE TITLE
How make domain works without port?

### ISSUE THREAD

**Issue by beny-harvestindo** [cleitonsouza01/docker-wordpress#4]
Hi i just wanna ask how domain wordpress without port. I just use SSL but it seem cant be accessed without port

**Comment by cleitonsouza01** [comment]
Hello @beny-harvestindo , thanks for asking. This project was created to use multiple domains and the way it works is using TCP port, if you just have one domain or have multiple domains but don't want to use TCP ports I recommend you to use docker-compose-letsencrypt-nginx-proxy-companion containers (more info in https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion). My project is based on it by the way.
